// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxREVmX6DMR4FBv4TGrQxByK7zFbmRKuo',
    appId: '1:233691877062:web:cff60538d24aef10b511c7',
    messagingSenderId: '233691877062',
    projectId: 'accessability-71ef7',
    authDomain: 'accessability-71ef7.firebaseapp.com',
    storageBucket: 'accessability-71ef7.firebasestorage.app',
    measurementId: 'G-2DQPN2XPWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPHlH9_2EntU7n7z_pw3NnMtwmCxBGjXM',
    appId: '1:233691877062:android:5b8832e1f3bde72db511c7',
    messagingSenderId: '233691877062',
    projectId: 'accessability-71ef7',
    storageBucket: 'accessability-71ef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu_n-XaVClkfu4pLU1Mn4u7SjveN6iiBI',
    appId: '1:233691877062:ios:a447c5d1078e85ecb511c7',
    messagingSenderId: '233691877062',
    projectId: 'accessability-71ef7',
    storageBucket: 'accessability-71ef7.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu_n-XaVClkfu4pLU1Mn4u7SjveN6iiBI',
    appId: '1:233691877062:ios:a447c5d1078e85ecb511c7',
    messagingSenderId: '233691877062',
    projectId: 'accessability-71ef7',
    storageBucket: 'accessability-71ef7.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxREVmX6DMR4FBv4TGrQxByK7zFbmRKuo',
    appId: '1:233691877062:web:7be3c1bb13e68647b511c7',
    messagingSenderId: '233691877062',
    projectId: 'accessability-71ef7',
    authDomain: 'accessability-71ef7.firebaseapp.com',
    storageBucket: 'accessability-71ef7.firebasestorage.app',
    measurementId: 'G-7YY40M05YV',
  );
}
